### ISSUE TITLE
Public Channels & Groups Fails to Sync 

### ISSUE THREAD

**Issue by MuhammadBayiz** [pwd491/Syncogram#1]
I started the syncing of both public channels & groups and Privacy settings, privacy setting gets completed just fine but public channels & groups fails after syncing 7-9 channels out of 415 without no errors just a red border line

**Comment by pwd491** [comment]
> I started the syncing of both public channels & groups and Privacy settings, privacy setting gets completed just fine but public channels & groups fails after syncing 7-9 channels out of 415 without no errors just a red border line

Hi, thank for your feedback. When you receive an error message, please hover over the error icon in the upper right corner, detailed information will appear there. Send a screenshot here

**Comment by pwd491** [comment]
I tested it and it works fine for me.
![image](https://github.com/pwd491/Syncogram/assets/68108301/46642e33-0829-4ea7-b8b9-bb956cd7805d)

**Comment by MuhammadBayiz** [comment]
I tested it today and it imported 56 channels out of 415 before it stops and fail. 
The error is:
(A wait of 2805 seconds is required (caused by JoinChannelRequest)) 
I think because it's a long list of channels and it joined the channels repeatedly telegram put a cooldpwn on the channel join request? I'm not sure

**Comment by pwd491** [comment]
> I tested it today and it imported 56 channels out of 415 before it stops and fail. The error is: (A wait of 2805 seconds is required (caused by JoinChannelRequest)) I think because it's a long list of channels and it joined the channels repeatedly telegram put a cool down on the JoinChannelRequest? I'm not sure

Telegram is actively fighting bots. I haven't tested with so many channels. I'll have to increase the pause from 12.5 seconds to 20 (3 channels per minute), but I'm still not sure if this will help. Unfortunately, I do not know exactly how many requests I can make per minute using this method, only trial and error methods. To avoid blocking your account, please do not try to synchronize channels anymore. Wait for the next version. Thanks!

**Comment by MuhammadBayiz** [comment]
You could add a setting for the pause so the user can change it if he has too many channels.
I did a quick search and couldn't find any info on joining channels limitations, so for an ultimate solution could you add a resume option for when it hits the limit you wait that much time and resume the process from where it stopped, this way we could finish the process in a few tries without trying over and over from the beginning. Thanks

**Comment by pwd491** [comment]
> You could add a setting for the pause so the user can change it if he has too many channels. I did a quick search and couldn't find any info on joining channels limitations, so for an ultimate solution could you add a resume option for when it hits the limit you wait that much time and resume the process from where it stopped, this way we could finish the process in a few tries without trying over and over from the beginning. Thanks

I don't think it's a good idea to let users adjust the frequency of sending requests to telegram themselves. Telegram is very sensitive to spam, so most users will ban their accounts. 

Saving progress is a great idea, I'm already working on it!

**Comment by MuhammadBayiz** [comment]
You're right since telegram doesn't have a clear clarification about the limit it might cause bans, so the decision for the frequency of the request should be yours.

**Comment by MuhammadBayiz** [comment]
> 
> Saving progress is a great idea, I'm already working on it!

 I'm looking forward to it, thanks a lot
